### ISSUE TITLE
Error when run ng serve

### ISSUE THREAD

**Issue by javist7** [aitboudad/ng-loading-bar#2]
I a'm using angula-cli for run and development my app (https://github.com/angular/angular-cli)

When i run ng serve (run liveReload server in development mode) i get an error 

Uncaught TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters (http://localhost:4200/main.bundle.js:48161:45)
    at Reflector.parameters (http://localhost:4200/main.bundle.js:48295:44)
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:4200/main.bundle.js:27527:54)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:4200/main.bundle.js:27492:26)
    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:4200/main.bundle.js:27267:28)
    at http://localhost:4200/main.bundle.js:27336:49
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/main.bundle.js:27329:44)
    at http://localhost:4200/main.bundle.js:27317:50
    at Array.forEach (native)

In production mode the error no

**Comment by aitboudad** [comment]
not sure if it's related to this repo,
I did a try and seems to be working fine see https://github.com/aitboudad/ng-loading-bar-demo-cli.git

**Comment by javist7** [comment]
When i commented NgLoadingBarModule.forRoot() my app work without error

**Comment by aitboudad** [comment]
seems related to angular itself just update your project deps to the latest version and it should work !
see https://github.com/aitboudad/ng-loading-bar-demo-cli/commit/595f128e8aea13a5b7c6e78cb103b436938f14b2
